// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransparenciaBot.Dados;

#nullable disable

namespace TransparenciaBot.Migrations
{
    [DbContext(typeof(TransparenciaBotDbContext))]
    [Migration("20260818020121_CriarEstruturaInicial")]
    partial class CriarEstruturaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransparenciaBot.Modelos.FalhaProcessamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("MensagemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RegistradaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MensagemId");

                    b.ToTable("FalhasProcessamento");
                });

            modelBuilder.Entity("TransparenciaBot.Modelos.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("IdentificadorWhatsApp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecebidaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorWhatsApp")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("TransparenciaBot.Modelos.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TelefoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TelefoneHash")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TransparenciaBot.Modelos.FalhaProcessamento", b =>
                {
                    b.HasOne("TransparenciaBot.Modelos.Mensagem", "Mensagem")
                        .WithMany("Falhas")
                        .HasForeignKey("MensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensagem");
                });

            modelBuilder.Entity("TransparenciaBot.Modelos.Mensagem", b =>
                {
                    b.HasOne("TransparenciaBot.Modelos.Usuario", "Usuario")
                        .WithMany("Mensagens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TransparenciaBot.Modelos.Mensagem", b =>
                {
                    b.Navigation("Falhas");
                });

            modelBuilder.Entity("TransparenciaBot.Modelos.Usuario", b =>
                {
                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
